export const AUTHENTICATION_LOGIN_REQUEST = "AUTHENTICATION_LOGIN_REQUEST";
export const AUTHENTICATION_LOGIN_SUCCESS = "AUTHENTICATION_LOGIN_SUCCESS";
export const AUTHENTICATION_LOGOUT_FAILED = "AUTHENTICATION_LOGOUT_FAILED";

export const AUTHORIZATION_REQUEST = "AUTHORIZATION_REQUEST";
export const AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED";
export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS ";

export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";
