export const REFRESH_MODEL_REQUEST = "REFRESH_MODEL_REQUEST";
export const REFRESH_MODEL_SUCCESS = "REFRESH_MODEL_SUCCESS";
export const REFRESH_MODEL_FAILED = "REFRESH_MODEL_FAILED";

export const SETUP_IFRAME_REF = "SETUP_IFRAME_REF";
