export const LOAD_BUILDINGS = "LOAD_BUILDINGS";
export const BUILDINGS_LOADED = "BUILDINGS_LOADED";
export const BUILDING_UPDATE = "BUILDING_UPDATE";
export const BUILDING_UPDATED = "BUILDING_UPDATED";