export const LOAD_SENSORS = "LOAD_SENSORS";
export const SENSORS_LOADED = "SENSORS_LOADED";
export const LOAD_SENSOR_EVENTS = "LOAD_SENSOR_EVENTS";
export const SENSOR_EVENTS_LOADED = "SENSOR_EVENTS_LOADED";
export const SENSOR_LOCATION_LOADED = "SENSOR_LOCATION_LOADED";
export const SENSOR_BUILDING_LOADED = "SENSOR_BUILDING_LOADED";
