export const FIELD_CHANGE = "FIELD_CHANGE";
export const BUILDING_CLEAR = "BUILDING_CLEAR";
export const BUILDING_SAVE = "BUILDING_SAVE";
export const BUILDING_ERROR = "BUILDING_ERROR";
export const BUILDING_CREATE = "BUILDING_CREATE";
export const BUILDING_NEW_SAVE = "BUILDING_NEW_SAVE"
